name: "Update Branch Values"
on:
  create:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: GitHub context
      run: echo "$GITHUB_CONTEXT"
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
    - name: Branch Name
      run: echo "${BRANCH_NAME}"

    - name: Extract Container name
      shell: bash
      run: echo "::set-env name=CONTAINER_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Container Name
      run: echo "${CONTAINER_NAME}"

    - name: Extract branch version
      shell: bash
      run: |
        echo "::set-env name=BRANCH_VERSION:: $(echo ${GITHUB_REF#refs/heads/} | sed 's/[^0-9.]*//g')"
    - name: Branch Version
      run: echo "${BRANCH_VERSION}"

    - name: Updating template/template.json
      run: |
          sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$BRANCH_NAME/template|" template/template.json
    - name: Updating template/tenant.json
      run: |
          sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$BRANCH_NAME/template|" template/tenant.json
    - name: Updating action.yml
      run: |
          sed -i "s|docker://mscet/azops:main|docker://mscet/azops:$CONTAINER_NAME|" action.yml
    - name: Updating AzOps.psd1
      run: |
          if [ -z $BRANCH_VERSION ]
          then
            echo "Not updating Brach Version. Value of Branch Version"
          else
            sed -i "s|ModuleVersion     = '0.0'|ModuleVersion     = '$BRANCH_VERSION'|" src/AzOps.psd1
          fi
    - name: Setup Git
      run: |
          git config --global user.email new-branch-commit@noreply.com
          git config --global user.name new-branch-commit
    - name: Add Changes
      run: |
          git add . && git commit -m 'System commit'
    - name: push commit
      run: |
          git push origin $BRANCH_NAME
