name: "Update Branch Specific Values"
on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: GitHub context
      run: echo "$GITHUB_CONTEXT"
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Test
      run: echo "${BRANCH_NAME}"
    - name: pwd
      run: pwd
    - name: ls
      run: ls $GITHUB_WORKSPACE -alH
    - name: Branch Name
      run: |
          sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/Azure/AzOps/$BRANCH_NAME/template|" template/template.json
