name: "Update Branch Values"
on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: GitHub context
      run: echo "$GITHUB_CONTEXT"
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Branch Name
      run: echo "${BRANCH_NAME}"
    - name: Updating template/template.json
      run: |
          sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$BRANCH_NAME/template|" template/template.json
    - name: Updating template/tenant.json
      run: |
          sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$BRANCH_NAME/template|" template/tenant.json
    - name: Setup Git
      run: |
          git config --global user.email system@noreply.com
          git config --global user.name system
    - name: Add Changes
      run: |
          git add . && git commit -m 'System commit'
    - name: push commit
      run: |
          git push origin $BRANCH_NAME
