name: "Build Container Image"
on:
  release:
    types: [created]
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to trigger docker push'
        required: true
        default: 'push'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pushtodockerregistry: ${{ steps.pushtodockerregistry.outputs.pushtodockerregistry }}
    steps:
      - name: Check whether push docker image to repository
        id: pushtodockerregistry
        env:
            PUSH_TO_DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        run: |
            echo "Enable Push to Docker Registry: ${{ env.PUSH_TO_DOCKER_REPOSITORY != '' }}"
            echo "::set-output name=pushtodockerregistry::${{ env.PUSH_TO_DOCKER_REPOSITORY != '' }}"

  build_push:
    needs: [build]
    if: github.event_name == 'push' && needs.build.outputs.pushtodockerregistry == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build_push_release
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}
        repository: ${{ secrets.DOCKER_REPOSITORY  }}
        add_git_labels: true
        tag_with_ref: true
        tags: ${{ github.sha }}, latest

  build_release:
    needs: [build]
    if: github.event_name == 'release' && needs.build.outputs.pushtodockerregistry == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    # - name: Extract Tag name
    #   shell: bash
    #   run: echo "::set-env name=TAG_NAME::${GITHUB_REF##*/}"
    # - name: Branch Name
    #   run: echo "${TAG_NAME}"
    # - name: Branch Version
    #   run: echo "${BRANCH_VERSION}"
    # - name: Updating template/template.json
    #   run: |
    #       sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$TAG_NAME/template|" template/template.json
    # - name: Updating template/tenant.json
    #   run: |
    #       sed -i "s|https://raw.githubusercontent.com/Azure/AzOps/main/template|https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$TAG_NAME/template|" template/tenant.json
    # - name: Updating action.yml
    #   run: |
    #       sed -i "s|docker://mscet/azops:main|docker://mscet/azops:$TAG_NAME|" action.yml
    # - name: Updating AzOps.psd1
    #   run: |
    #       sed -i "s|ModuleVersion     = '0.0'|ModuleVersion     = '$TAG_NAME'|" src/AzOps.psd1
    # - name: Setup Git
    #   run: |
    #       git config --global user.email release-commit@noreply.com
    #       git config --global user.name system
    # - name: Add Changes
    #   run: |
    #       git add . && git commit -m 'System commit'
    # - name: push commit
    #   run: |
    #       git push origin $TAG_NAME
    - name: build_push_release
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}
        repository: ${{ secrets.DOCKER_REPOSITORY }}
        add_git_labels: true
        tag_with_ref: true
        tags: ${{ github.sha }} , ${{ github.event.release.tag_name }}