name: "Build Container Image"
on:
  push:
  release:
    types: [created]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        repository: uday31in/azops/${{ github.ref }}
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
        tags: ${{ github.sha }}