name: "Build Container Image"
on:
  release:
    types: [created]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set repository env
      run: echo ::set-env name=repository::${GITHUB_REPOSITORY,,}
    - name: build_push
      uses: docker/build-push-action@v1
      with:
        username: system
        password: ${{ secrets.GITHUB_TOKEN  }}
        registry: docker.pkg.github.com
        repository: ${{env.repository}}/${{ github.event.release.tag_name }}
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
        tags: ${{ github.sha }}